// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:2d5233ea-8d81-4ff1-a5fd-167cdc698e31",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_zO51xo8Ei",
    "aws_user_pools_web_client_id": "3cusot5nkhc4903h49m36rp2rr"
};


export default awsmobile;
