service: cad-sls
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-2:*:*"
  stage: dev
  region: eu-west-2
  environment:
    USER_TABLE_NAME: ${self:service}-${self:provider.stage}-usersCAD

functions:
  hello:
    handler: getHandler.hello
    events:
     - http:
         path: /default
         method: get
         cors: true
  imageResize:
    handler: getHandler.imageResize
    events:
     - http:
         path: /imageResize
         method: get
         cors: true
  postUser:
    handler: postHandler.postUser
    events:
     - http:
         path: /postUser
         method: post
         cors: true
resources:
  Resources:
    usersCAD:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:service}-${self:provider.stage}-usersCAD
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
